module.exports = {
  STATUS_CODE: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UN_AUTHORIZED: 401,
    PAGE_NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
  },
  SOCIAL_TYPE: {
    FACEBOOK: 'FACEBOOK',
    GOOGLE: 'GOOGLE',
    LINKDIN: 'LINKDIN',
    APPLE: 'APPLE'
  }
};
